prefix wn30: <https://w3id.org/own-pt/wn30/schema/>
prefix nomlex: <https://w3id.org/own-pt/nomlex/schema/>

select ?w1 ?w2 ?p ?sid1 ?sid2 ?g1 ?g2 ?ws1 ?ws2
{
  ?ws1 ?p ?ws2 .
  ?p rdfs:subPropertyOf nomlex:morphosemanticLink .
  
  ?ptss1 wn30:containsWordSense ?ws1 .
  ?ptss2 wn30:containsWordSense ?ws2 .

  ?ws1 wn30:word/wn30:lexicalForm ?w1 .
  ?ws2 wn30:word/wn30:lexicalForm ?w2 .
  
  ?ptss1 skos:inScheme <http://logics.emap.fgv.br/wn/> .
  ?ptss2 skos:inScheme <http://logics.emap.fgv.br/wn/> .
  
  ?ss1 owl:sameAs ?ptss1 ;
       wn30:gloss ?g1 ;
       wn30:synsetId ?sid1 .
  
  ?ss2 owl:sameAs ?ptss2 ;
       wn30:gloss ?g2 ;
       wn30:synsetId ?sid2 .
}
order by ?p